version: '3'

volumes:
  app_database: {}
  app_cache: {}

services:
  nginx:
    image: matiux/nginx:symfony-2.0.0
    # build:
    #   context: ./docker/nginx/Php
    #   args:
    #     - FRAMEWORK=${FRAMEWORK}
    ports:
      - '8080:80'
    depends_on:
      - php
    volumes:
      - ./docker/logs/nginx/:/var/log/nginx
      - ./:/var/www/app
  php:
    image: matiux/php:7.1-fpm-2.0.0
    #build: ./docker/php/7.1-fpm
    tty: true # -t option in docker
    stdin_open: true # -i option in docker
    hostname: app_hostname
    volumes:
      - ./:/var/www/app
    environment:
      - APP_ENV=${APP_ENV}
  servicedb:
    image: mysql:5.7
    restart: always
    volumes:
      # - ./docker/data/db:/var/lib/mysql
      - app_database:/var/lib/mysql
      - ./docker/database/custom.cnf:/etc/mysql/conf.d/custom.cnf
    environment:
      - MYSQL_ROOT_PASSWORD=${DOCKER_MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=app_db
    ports:
      - '3307:3306'
    command: mysqld --sql_mode="" #Per mysql, non serve per mariadb
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    depends_on:
      - servicedb
    environment:
      - PMA_HOST=servicedb
  servicememcached:
    image: memcached:latest
    volumes:
      # - ./docker/data/memcached:/var/lib/memcached
      - app_cache:/var/lib/memcached
  # redis_db:
  #   image: redis:alpine
  #   #command: redis-server --requirepass redis
  #   ports: ["6379"]
