version: '3'

volumes:
  app_database: {}
  app_cache: {}

services:
  web:
    image: nginx:latest
    ports:
      - 8080:80
    depends_on:
      - php
    volumes:
      - ./:/var/www/app
      - ./docker/nginx/symfony-4.conf:/etc/nginx/conf.d/default.conf
      - ./docker/data/logs/nginx/:/var/log/nginx
      #- ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
 
  php:
    build:
      context: ./docker/php/alpine/7.2.11-fpm/base
      dockerfile: Dockerfile
    hostname: app_hostname
    volumes:
      - ./:/var/www/app
      - ./docker/data/shell_history:/home/utente/shell_history

  database:
    image: mysql:5.7
    # restart: always
    volumes:
      - app_database:/var/lib/mysql
      - ./docker/database/mysql/custom.cnf:/etc/mysql/conf.d/custom.cnf
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=app_db
    ports:
      - '3307:3306'
    command: mysqld --sql_mode="" #Per mysql, non serve per mariadb
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    depends_on:
      - database
    environment:
      - PMA_HOST=database

  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8081:8080

  servicememcached:
    image: memcached:latest
    volumes:
      - app_cache:/var/lib/memcached
  
  # redis_db:
  #   image: redis:alpine
  #   #command: redis-server --requirepass redis
  #   ports: ["6379"]